name: Build

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches:
    - main
    - features/*
  # pull_request:
  #   branches: [ main ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure environment
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Build the project
      - name: Call build script
        run: ./build.sh

      # Prepare artifact(s)
      # - Copy license to ./dist so the artifact zip contains something else.
      #   This is to avoid the solution zip auto extracting when double clicked.
      - run: cp ./LICENSE ./dist
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}__extract_this_zip
          path: ./dist/*
          retention-days: 15
